# docker ps -a
# docker-compose -f docker-compose.yml up -d
# docker-compose -f docker-compose.yml down -v
# подключиться к контейнеру созданной бд можно командой:
# docker exec -it solanabot_postgres psql --username=solanabot --dbname=solanabot


version: '3.8'

services:

  postgres:
    image: postgres:14-alpine
    container_name: solanabot_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: solanabot
      POSTGRES_USER: solanabot
      POSTGRES_DB: solanabot
    volumes:
      - ../var/postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: solanabot_pgadmin4
  #   restart: always
  #   ports:
  #     - '8888:80'
  #   user: '$UID:$GID'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: solanabot
  #   volumes:
  #     - ../var/pgadmin-data:/var/lib/pgadmin

  # redis:
  #   image: redis:latest
  #   container_name: solanabot_redis
  #   command: redis-server
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - ../var/redis:/var/lib/redis
  #     - ../var/redis-config:/usr/local/etc/redis/redis.conf

volumes:
  postgres-data:
  # pgadmin-data:
  # redis:
  # redis-config:
