# Generated by Django 5.0.6 on 2024-05-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='address',
            new_name='wallet_address',
        ),
    ]
