# Generated by Django 5.0.6 on 2024-05-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data', models.TextField(verbose_name='QR Code Data')),
                ('qr_image', models.BinaryField(verbose_name='QR Code Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
