# Generated by Django 5.0.6 on 2024-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_address_wallet_wallet_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created'], 'verbose_name': 'wallet', 'verbose_name_plural': 'wallets'},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(max_length=200, verbose_name='Wallet address'),
        ),
    ]
