# Generated by Django 5.0.6 on 2024-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.TextField(verbose_name='QR Code Image'),
        ),
    ]
