# Generated by Django 5.0.6 on 2024-06-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_qrcode_qr_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
