# Generated by Django 5.0.6 on 2024-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_options_alter_wallet_wallet_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['created'], 'verbose_name': 'wallet', 'verbose_name_plural': 'wallets'},
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_number_solana_derivation_path',
            field=models.PositiveIntegerField(default=0, verbose_name='Last number derivation path for Solana'),
        ),
    ]
