# Generated by Django 5.0.6 on 2024-05-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='last_number_solana_derivation_path',
            new_name='solana_derivation_path_number',
        ),
    ]
