# Generated by Django 5.0.6 on 2024-05-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_last_number_solana_derivation_path_wallet_solana_derivation_path_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='solana_derivation_path_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Solana derivation path'),
        ),
    ]
