# Generated by Django 5.0.6 on 2024-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_solana_derivation_path_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=50, verbose_name='Статус')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='Transaction id')),
                ('sender', models.CharField(blank=True, max_length=200, verbose_name='Sender')),
                ('recipient', models.CharField(blank=True, max_length=200, verbose_name='Recipient')),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Amount')),
                ('transaction_time', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Transaction time')),
                ('slot', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Transaction slot')),
                ('transaction_status', models.CharField(blank=True, max_length=200, verbose_name='Transaction status')),
                ('transaction_error', models.CharField(blank=True, max_length=200, verbose_name='Transaction error')),
                ('wallet', models.ManyToManyField(related_name='transactions', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['transaction_time'],
            },
        ),
    ]
