# Generated by Django 5.0.6 on 2024-05-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='post_balances',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Post-balances'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pre_balances',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Pre-balances'),
        ),
    ]
