# Generated by Django 5.0.6 on 2024-05-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_transaction_amount_transaction_post_balances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(max_length=200, unique=True, verbose_name='Wallet address'),
        ),
    ]
