# Generated by Django 5.0.6 on 2024-05-18 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_wallet_wallet_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='Transaction id'),
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ManyToManyField(related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Wallet owners'),
        ),
    ]
