# Generated by Django 5.0.6 on 2024-05-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_transaction_transaction_id_remove_wallet_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_error',
            new_name='transaction_err',
        ),
    ]
