# Generated by Django 5.0.6 on 2024-05-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_solana_derivation_path',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last derivation path for Solana'),
        ),
    ]
