# Generated by Django 5.0.6 on 2024-05-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_last_solana_derivation_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_solana_derivation_path',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Last derivation path for Solana'),
            preserve_default=False,
        ),
    ]
