# Generated by Django 5.0.6 on 2024-05-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_last_solana_derivation_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_solana_derivation_path',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Last number derivation path for Solana'),
        ),
    ]
