# Generated by Django 5.0.6 on 2024-05-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_last_solana_derivation_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_solana_derivation_path',
        ),
        migrations.AddField(
            model_name='user',
            name='last_number_solana_derivation_path',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Last number derivation path for Solana'),
        ),
    ]
